team_pic_mapper = {
    "Víkingur R.":"VÍKR",
    "Valur":"Valur",
    "Stjarnan":"STJA",
    "Breiðablik":"BREI",
    "KA":"KA",
    "FH":"FH",
    "ÍA":"IA",
    "Keflavík":"KEF",
    "Leiknir R.":"LEI",
    "KR":"KR",
    "Afturelding":"AFT",
    "Þróttur R.":"ÞRO",
    "Þór/KA":"ÞORKA",
    "Selfoss":"SEL",
    "ÍBV":"IBV",
    "Fram":"FRA",
    "Vestri":"VES",
    "Fylkir":"FYL",
    "HK":"HK"
}